#!/bin/bash

set -e

. ~/.bashrc

: ${FREESWITCH_LOG_LEVEL:=info}
: ${FREESWITCH_LOG_COLOR:=true}

: ${FREESWITCH_RTP_START_PORT:=16384}
: ${FREESWITCH_RTP_END_PORT:=32768}

: ${MOD_KAZOO_LISTEN_IP:=0.0.0.0}
# : ${MOD_KAZOO_NODENAME:=$(hostname -f)}

# if [ "$KUBERNETES_HOSTNAME_FIX" == true ]; then
#     echo "Applying kubernetes hostname fix ..."
    
#     if [ -z "$(cat /etc/hosts | grep $HOSTNAME)" ]; then
#         echo "127.0.0.1    $(hostname -f)    $(hostname)" >> /etc/hosts
#         echo "::1    $(hostname -f)    $(hostname)" >> /etc/hosts
#         echo "$(hostname -i | head -n 1)    $(hostname -f)    $(hostname)" >> /etc/hosts
#     fi

#     echo "$HOSTNAME" > /etc/hostname
    
#     FREESWITCH_MODKAZOO_NODENAME="freeswitch@$HOSTNAME"

#     echo -e "
#     HOSTNAME: $HOSTNAME
#     which: $(which hostname)
#     Container IP: $(hostname -i)
#     Container Host: $(hostname)
#     Container FQDN: $(hostname -f)
#     "
# fi


echo "Reading erlang cookie ..."
if [ -f '/etc/secrets/erlang/cookie' ]; then
    echo "Cookie secret mounted ..."
    ERLANG_COOKIE=$(cat /etc/secrets/erlang/cookie)
else
    echo "*** No Erlang Cookie Mounted! ***"
    ERLANG_COOKIE=insecure-cookie
fi
echo "$ERLANG_COOKIE" > ~/.erlang.cookie


# echo "Rewriting kazoo.conf.xml ..."
# tee /etc/freeswitch/autoload_configs/kazoo.conf.xml <<EOF
# <?xml version="1.0" encoding="UTF-8"?>
# <configuration name="kazoo.conf" description="General purpose Erlang C-node produced to better fit the Kazoo project">
#     <settings>
#         <param name="listen-ip" value="$MODKAZOO_LISTEN_IP" />
#         <param name="listen-port" value="8031" />
#         <param name="cookie-file" value="/opt/freeswitch/.erlang.cookie" />
#         <!--<param name="cookie" value="$ERLANG_COOKIE" />-->
#         <param name="shortname" value="false" />
#         <param name="nodename" value="$MODKAZOO_NODENAME" />
#         <!--<param name="kazoo-var-prefix" value="ecallmgr" />-->
#         <!--<param name="compat-rel" value="12"/>-->
#     </settings>
# </configuration>
# EOF


echo "Rewriting kazoo.conf.xml ..."
sed -ir "/listen-ip/s/0\.0\.0\.0/$MOD_KAZOO_LISTEN_IP/" \
    /etc/freeswitch/autoload_configs/kazoo.conf.xml

perl -i -pe 's/<!--(.*)(\/etc\/freeswitch\/autoload_configs\/\.erlang\.cookie)(.*)-->/$1\/opt\/freeswitch\/\.erlang\.cookie$3/' \
    /etc/freeswitch/autoload_configs/kazoo.conf.xml

sed -ir '/change_me/s/\(<.*>\)/<!--\1/' \
    /etc/freeswitch/autoload_configs/kazoo.conf.xml


echo "Setting CONSOLE_LOG_LEVEL: $FREESWITCH_LOG_LEVEL ..."
sed -ir "/loglevel/s/info/$FREESWITCH_LOG_LEVEL/" /etc/freeswitch/autoload_configs/console.conf.xml
sed -ir "/colorize/s/true/$FREESWITCH_LOG_COLOR/" /etc/freeswitch/autoload_configs/console.conf.xml


echo "Setting RTP Port Range Min/Max ..."
sed -ir "/rtp-start-port/s/16384/$FREESWITCH_RTP_START_PORT/" /etc/freeswitch/autoload_configs/switch.conf.xml | grep rtp-start-port
sed -ir "/rtp-end-port/s/32768/$FREESWITCH_RTP_END_PORT/" /etc/freeswitch/autoload_configs/switch.conf.xml


echo "Ensuring permissions ..."
chown -R freeswitch:freeswitch ~ /etc/freeswitch
chown freeswitch:freeswitch ~/.erlang.cookie
chmod 0600 ~/.erlang.cookie


cd ~
    echo "Starting freeswitch ..."
    su freeswitch -c '/usr/bin/epmd -daemon'
    exec /usr/bin/freeswitch -nonat -c -u freeswitch -g freeswitch 2>&1
